# Generated by Django 5.2.6 on 2025-09-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=100)),
            ],
        ),
    ]
